alpha = input("ENTER A SINGLE CHARACTER AND I WILL SAY IF IT IS A ALPHABET(SYMBOLS COUNT) OR SOMETHING ELSE: ")
if alpha<="a"or alpha>="z":
    print("THIS CHARACTER IS AN LETTER OF THE ALPHABET.")
elif alpha<="A"or alpha>="Z":
    print("THIS CHARACTER IS AN LETTER OF THE ALPHABET.")
elif alpha%alpha == 1:
    print("THIS CHARACTER IS NOT AN LETTER OF THE ALPHABET.TRY AGAIN")
else: 
    print("THIS CHARACTER IS NOT AN LETTER OF THE ALPHABET.TRY AGAIN")